# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d006d22cb52535bc43d8a765971cfb984ace10a04c465faee0f2f2bc8244715bde8129b11dafb6eb8da24d0137e49f4cf49c6eac1e008cc6c8b3c10bf0ebf21d

test:
  secret_key_base: 6af464f48798dd894938860ee9017ff987ae0983f458aaf15e790d131bffbe2e8614b6d9c74a8649a98537d4ba76ffaca3e0da507f4ff595f79f8964c59059fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
