# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf356ef9c923568f5d094704d4a53fda177f435f2b806b04e7619b98e22f06dff0a9a0fceb3b1acb4ea48a2beffb4d51b85d9ff09b408110db688ec58627b800

test:
  secret_key_base: 51324259a299245743e8fe4b389dd30783ea454b500b30e6c063d0801548f6020dd66903b50e10e387779bfe23d5c842d42db04e69acdc348139cac5b82dcb58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
